name: ynot_torch1p6
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - astropy
  - tqdm
  - pandas
  - jupyter
  - ipython
  - seaborn
  - scikit-learn
  - pyarrow
  - pytorch>=1.6
  - torchvision
  - pytest
  - pip
  - cmake
  - sphinx
  - celerite
  - black
  - pip:
    - kornia
    - pykeops
    - recommonmark
    - tensorboard
    - lacosmic
