name: ynot_cuda10p2
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib>3.1.1
  #- pytorch
  #- torchvision
  #- cudatoolkit=10.0
  - tqdm
  - astropy
  - pandas
  - jupyter
  - ipython
  - seaborn
  - scikit-learn
  - pip
  - pyarrow
  - pytest
  - twine
