name: ynot_jax
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib>3.1.1
  - astropy
  - tqdm
  - pandas
  - jupyter
  - ipython
  - seaborn
  - scikit-learn
  - pyarrow
  - pytorch=1.6
  - torchvision
  - pip
  - pip:
    - emcee
    - gpustat
    #- fbpca
    # Manually install jax!
